name: birds_learning_network
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dots_indicator: ^2.1.0
  flutter_svg: ^2.0.2
  http: ^0.13.5
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  email_validator: ^2.1.17
  device_info_plus: ^8.1.0
  shared_preferences: ^2.0.18
  country_picker: ^2.0.19
  path: ^1.8.3
  flutter_otp_text_field: ^1.1.0+2
  flutter_secure_storage: ^8.0.0
#  webview_flutter: ^4.4.2
#  flutter_facebook_auth: ^5.0.8
  dropdown_button2: ^1.9.2
  url_launcher: ^6.1.12
  image_picker: ^0.8.7
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  flutter_html: ^3.0.0-alpha.6
  chewie: ^1.4.0
  video_player: ^2.6.0
  sqflite: ^2.3.0
  youtube_player_flutter: ^8.1.2
  shimmer: ^2.0.0
  flash: ^2.0.5+1
  flutter_stripe: ^9.2.1
  flutter_share_me: ^1.4.0
  percent_indicator: ^4.2.3
  uuid: ^4.1.0
#  pod_player: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.2

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/birds_logo.jpg"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

